# This file was generated by GoReleaser. DO NOT EDIT.
cask "kvx" do
  version "0.8.2"

  on_macos do
    on_intel do
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "8f4b6d6df73b06a4805d17aff1cfb2f4f677f2fa6bb046d9c9025588477e8f6e"
    end
    on_arm do
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Darwin_arm64.tar.gz"
      sha256 "b37c58c45740aa35844e648dae4b5767cf2121ce777d617ac9a62078cd52fa1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Linux_x86_64.tar.gz"
      sha256 "d4aacf73763372f7783c0c97a614cae8a2ab0c81c96a78d07381185009f98aec"
    end
    on_arm do
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Linux_arm64.tar.gz"
      sha256 "45f0e893622ee11748cef31bd31e422ef70a86edf485a9f99064f9f06cd186df"
    end
  end

  name "kvx"
  desc "Terminal-based UI for exploring structured data interactively"
  homepage "https://github.com/oakwood-commons/kvx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kvx"

  # No zap stanza required

end
