# This file was generated by GoReleaser. DO NOT EDIT.
cask "kvx" do
  version "0.16.1"

  on_macos do
    on_intel do
      sha256 "2272c62cbbe7a83aaba1baa5575dee918199ad3635e7f88ba85341cae8ce5930"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cec0b9691860b9fdae918e3e5f986b70819c432e63e62fbb5f004a98d5c9d591"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "738df5da4d604e4ad63dd93a8aa2ff366644d2a837f4d5c5b12273bac306798a"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "759e969d5ccee8137c0a524b30a3c3e1269ed010923119cb0edb5c4485285a76"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kvx"
  desc "Terminal-based UI for exploring structured data interactively"
  homepage "https://github.com/oakwood-commons/kvx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kvx"

  # No zap stanza required

end
