# This file was generated by GoReleaser. DO NOT EDIT.
cask "kvx" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "44440e39bac7d49161ebdfb5e3931a84c932f6e1c7c3c48e6d13a98cd03d127f"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9e6134b28b6156ac5eb9ed79233b1279c27519f23a44db44e9d3fc3147e4547a"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "59614cb9f4b8a5c64ecea9be3458fd19abb69f8ca1517ff0c2cae3a6db2067e7"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "871580d932fc350c2b30d0532f0f6d876f52769e9278f8e90dd110fc006c705a"
      url "https://github.com/oakwood-commons/kvx/releases/download/v#{version}/kvx_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kvx"
  desc "Terminal-based UI for exploring structured data interactively"
  homepage "https://github.com/oakwood-commons/kvx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kvx"

  # No zap stanza required

end
