# This file was generated by GoReleaser. DO NOT EDIT.
cask "scafctl" do
  name "scafctl"
  desc "A configuration discovery and scaffolding tool using CEL for dynamic evaluation"
  homepage "https://github.com/oakwood-commons/scafctl"
  version "0.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scafctl"

  on_macos do
    on_intel do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Darwin_x86_64.tar.gz"
      sha256 "c4d34efe367a8fe06ff6a205e25b9109577bb95783161c0e6d7046c4648c006c"
    end
    on_arm do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Darwin_arm64.tar.gz"
      sha256 "9a7005d87e1c19b77811e37c607f31cf96ee2f90874e617c6658ec0243cdacd4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Linux_x86_64.tar.gz"
      sha256 "fe90265fa8a23c75f143c5194d1b157f9f86a5a5371a6a1b9534a1fb8c2f7a9c"
    end
    on_arm do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Linux_arm64.tar.gz"
      sha256 "855b004cea16299d3551f13a504a5398c1f07602864b7a3da35a57ffb36e5a89"
    end
  end

  # No zap stanza required
end
