# This file was generated by GoReleaser. DO NOT EDIT.
cask "scafctl" do
  name "scafctl"
  desc "A configuration discovery and scaffolding tool using CEL for dynamic evaluation"
  homepage "https://github.com/oakwood-commons/scafctl"
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scafctl"

  on_macos do
    on_intel do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Darwin_x86_64.tar.gz"
      sha256 "d5027a3d791a0aec01d06803cd01519199c0708519fb03d7d98dddbd3069a340"
    end
    on_arm do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Darwin_arm64.tar.gz"
      sha256 "c4e9685f553459d11cca2709560bfd8708abf947b2c69e094f2deb2c29bd9e59"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Linux_x86_64.tar.gz"
      sha256 "1bb973d65354d2292e9418399c592bc22ebab6f4ee62abe89f0b5fe8e9eefc1a"
    end
    on_arm do
      url "https://github.com/oakwood-commons/scafctl/releases/download/v#{version}/scafctl_#{version}_Linux_arm64.tar.gz"
      sha256 "0fb1fa40bc93a544945eea6fb218c82ea977bafb021dba29a0b8d74ea256967d"
    end
  end

  # No zap stanza required
end
